version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: content-range
    versions:
    - ">= 2.a, < 3"
  - dependency-name: "@algoan/pubsub"
    versions:
    - 4.5.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@nestjs/testing"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/microservices"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/core"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/common"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@nestjs/platform-express"
    versions:
    - 7.6.11
    - 7.6.12
    - 7.6.13
    - 7.6.14
    - 7.6.15
    - 7.6.7
    - 7.6.8
    - 7.6.9
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
    - 8.2.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
  - dependency-name: jwt-decode
    versions:
    - 3.1.2
  - dependency-name: content-range
    versions:
    - 1.1.1
  - dependency-name: tslint
    versions:
    - 6.1.3
