# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1
orbs:
  release-workflows: 'hutson/library-release-workflows@4.3.3'
workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - deliver:
          context: semantic_release
          filters:
            branches:
              only: master
          requires:
            - test
      - deploy:
          context: semantic_release
          filters:
            branches:
              only: master
          requires:
            - deliver



imageA: &defaults
  working_directory: ~/tmp
  docker:
    - image: yelloan/node-docker:lts
  environment:
    NODE_ENV: test

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm ci
      - run:
          name: Lerna bootstrap the packages
          command: npx lerna bootstrap
      - run:
          name: Lint source code
          command: npm run lint
      - run:
          name: Run test script in all packages that contains that script
          command: npm run test
      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/tmp
          paths: .
  deliver:
    test:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 1a:a9:39:20:ed:37:35:23:82:d7:d8:62:2e:53:d3:8a
      - run: >-
          git config --global user.email "${GH_BOT_EMAIL}" && git config --global user.name "${GH_BOT_FULLNAME}"
      - attach_workspace:
          at: ~/tmp
      - run: npx lerna version --conventional-commits --yes
      - persist_to_workspace:
          root: ~/tmp
          paths: .
  deploy:
    test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc 
      - run: npx lerna publish from-git --yes