# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Get GCloud CLI to install pubsub emulator
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'beta,pubsub-emulator'
      - run: npm i -g npm@9
      - run: npm ci
        name: Install root dependencies
      - run: npx lerna bootstrap --hoist
        name: Install all dependencies and symlinks using lerna bootstrap
      - run: npm run lint
        name: Lint all packages
      - run: npm run test:cov:all
        name: Launch tests for each package
