# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Get GCloud CLI to install pubsub emulator
        uses: google-github-actions/setup-gcloud@master
      - name: Update GCloud Components
        run: gcloud components update --quiet
      - name: Install GCloud beta
        run: gcloud components install beta --quiet
      - name: Install pubsub-emulator
        run: gcloud components install pubsub-emulator --quiet
      - run: npm i
      - run: npx lerna bootstrap
      - run: npm run lint
      - run: npm run test:cov:all
